/* Generated by maintenance/generate_embedded_magic.ps1. */
#ifndef FILEMAGIC_EMBEDDED_MAGIC_H
#define FILEMAGIC_EMBEDDED_MAGIC_H

#include <stddef.h>

extern const unsigned char filemagic_embedded_magic[];
extern const size_t filemagic_embedded_magic_size;

#endif
